//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApplication
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bottom_button_bar_gradient = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int redlaser_logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int viewfinder_green = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int viewfinder_white = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int MyButton = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int SDK_Version_TextField = 2131099658;
			
			// aapt resource value: 0x7f060000
			public const int barcodeText = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int barcodeType = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int btn_clearList = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int btn_multiscan = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int btn_options = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int btn_singlescan = 2131099654;
			
			// aapt resource value: 0x7f060023
			public const int button_done = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int button_request_image = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int button_toggle_torch = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int buttons_view = 2131099680;
			
			// aapt resource value: 0x7f060002
			public const int empty_view = 2131099650;
			
			// aapt resource value: 0x7f06001b
			public const int hint_text = 2131099675;
			
			// aapt resource value: 0x7f060005
			public const int listView1 = 2131099653;
			
			// aapt resource value: 0x7f06001d
			public const int num_found_text = 2131099677;
			
			// aapt resource value: 0x7f06001f
			public const int overlay_logo = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int overlay_text = 2131099678;
			
			// aapt resource value: 0x7f06001a
			public const int preview_frame_overlay = 2131099674;
			
			// aapt resource value: 0x7f060012
			public const int toggle128 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int toggle39 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int toggle93 = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int toggleCodabar = 2131099672;
			
			// aapt resource value: 0x7f060015
			public const int toggleDataMatrix = 2131099669;
			
			// aapt resource value: 0x7f06000b
			public const int toggleEAN13 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int toggleEAN2 = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int toggleEAN5 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int toggleEAN8 = 2131099660;
			
			// aapt resource value: 0x7f060017
			public const int toggleITF = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int toggleOrientation = 2131099673;
			
			// aapt resource value: 0x7f060011
			public const int toggleQR = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int toggleRSS14 = 2131099670;
			
			// aapt resource value: 0x7f060010
			public const int toggleSticky = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int toggleUPC = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int udid_string = 2131099651;
			
			// aapt resource value: 0x7f06001c
			public const int view_finder = 2131099676;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int barcodelistlayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int jmain = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int options_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int preview_overlay_landscape = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int preview_overlay_new_portrait = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int preview_overlay_old_portrait = 2130903046;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int beep = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05000a
			public const int Hello = 2131034122;
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int code_types = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int done_button = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int empty_history = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int getImage_button = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int guidance_string = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int light = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int logo_message = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int overlay_logo_contentdescription = 2131034119;
			
			private String()
			{
			}
		}
	}
}
